### ISSUE TITLE
Fix the hacker lounge stools

### ISSUE THREAD

**Issue by akf** [osbridge/planning#176]
The ottomans/stools for the hacker lounge fail under load. Need security upgrades prior to the event.

**Comment by 1337807** [comment]
There are a couple in the storage unit that have already been damaged. If we fix those then onsite it will likely suffice to label the rest of them with "DO NOT SIT" masking tape on the edges or we could reinforce them with boards underneath. That last option seems to make less sense given that it would be hard to be sure they could support people sitting on them even if we do upgrade them.

**Comment by neophiliac** [comment]
Are there some inexpensive cubes that could function as an ottoman or a stool, and should we replace the ottomans with those as they fail? The Poangs are $60 or $90 on the IKEA site. The Bosnas doesn't match, but has room for storage and the product page (http://www.ikea.com/us/en/catalog/products/80266699/#/20266701) shows someone sitting on it (so maybe they'll replace them if they break because people sit on them?). And it's only $15.

**Comment by akf** [comment]
I'm going to bring this one to the mailing list, and if we don't come to a conclusion we can bring it up in next week's meeting. That still gives us a few days to work in an IKEA run and do the required assembly.

**Comment by ChrisFreeman** [comment]
Is there a model name or number of the broken lounge stools? I can do some research into a hardware fix or maybe fashion something in my shop. I have a bunch of 1/2" MDF I can perhaps cut up into supports.

**Comment by akf** [comment]
I'm pretty sure they're these (they'd have to be, although IKEA might have made some subtle change to the design since we got them a few years ago): http://www.ikea.com/us/en/catalog/products/S19825153/

If you look at the assembly instructions PDF, you can see that there's a board that basically fits into slots in the frame. The problem was that this board would flex and fall out of the slot ... so I think attaching it to the frame with brackets would solve the problem for stools that aren't actually broken. (Doing this should be okay, since we don't disassemble them for storage.) 

There was a theory that some of the boards hadn't been put in place correctly and that made them more prone to come out. 

@1337807  would remember better than I what actually broke, but I think we have at least one case where the board itself broke. 

I think these boards were roughly 1/4 inch thick, but I'd advise you actually get to look at one rather than trust my memory.

**Comment by ChrisFreeman** [comment]
Right. The thin board flexing is clearly the issue. I see three or four possible ways to fix them: adding simple bracket, adding cross brace support under flexing panel, replace/supplement panel with stiff thicker material, or a combo. I can do this. 

I'll need to pickup them up later on Sunday or Early next week.

**Comment by akf** [comment]
@kcomandich, would you coordinate with @ChrisFreeman to get him access to the hacker lounge stools? I'm happy to help if your schedules don't mesh. 

I haven't brought the idea of buying replacements to the list as I said I would, but I think I'll hold off until Chris has had a chance to look at what we have. We're short enough of funds that I doubt we'll want to do that anyway.

**Comment by kcomandich** [comment]
@ChrisFreeman now has the 10 unbroken footstools. I didn't see the 2 broken ones in the storage unit. If they are there, they are hidden underneath other things.

**Comment by ChrisFreeman** [comment]
Good News: The footstool structural upgrade is sound. I can comfortably stand on it!

Bad News: Turns out the seat width span dimension varies from footstool to footstool with over an inch difference between largest and smallest. Not realizing this, I had developed my plans and templates and cut all the wood based on a single size. And thus could only assemble that one.

Good News: I (very) luckily had chosen the largest one for my template. This means I only have to trim a few pieces to re-fit the smaller footstools

Bad News: I didn't discover this until too late in the day to run the table saw due to noise issues  (requires an open garage door).

Good News: I can finish the remaining assembly Tuesday night.

Bonus: I laundered the padding covers. They look (and smell!) much better!
