### ISSUE TITLE
Volunteer Management

### ISSUE THREAD

**Issue by k4y3ff** [osbridge/planning#295]
## Pre-Conference
- [ ] Add @kpfell to `volunteers@osbridge` email account
- [x] Update copy for the [/get-involved page](http://opensourcebridge.org/get-involved/)
- [x] Switch from WuFoo form to Google Form
  - [x] Make sure email notifications get sent when spreadsheet associated with Google Form is updated
  - [x] Make sure that the spreadsheet associated with the Google Form is visible to all people on the organizing team
  - [x] Make sure the Google Form displays a meaningful note to people when they submit their information
- [x] Create a "call to volunteers" Google Group for pre-conference requests
- [ ] Move volunteer interest contact information @ChrisFreeman has into a Google Sheet in the "Volunteer Coordination" folder in Google Drive with appropriate permissions
- [ ] Send single email to aforementioned volunteer contacts asking if they are interested in hearing about future volunteering opportunities
  - [ ] Invite interested volunteers to Google Group
  - Old contact info will be tl;dr archived in aforementioned Google Spreadsheet; future volunteer info sent to Google Group
- [ ] Invite people to Google Group who have expressed interest in volunteering via the [/get-involved page](http://opensourcebridge.org/get-involved/)
- [ ] Determine pre-conference volunteer needs
- [ ] Send out pre-conference volunteer requests via the aforementioned Google Group
- [ ] Email local code schools and universities about discount codes and volunteering
- [ ] Determine day-of-conference volunteer needs
- [ ] Update the volunteer app with 2016 dates and contact info
- [ ] Update the volunteer app with day-of-conference volunteer shifts
- [ ] Make the volunteer app public again 🙌 
## Around the start of the conference
- [ ] Determine unfulfilled day-of-conference volunteer needs
- [ ] Find volunteers to fill unfilled day-of-conference needs
  - I, @kpfell, do not currently know what this will entail. Maybe reallocating floaters?

/cc ✨  @ChrisFreeman ✨

**Comment by kpfell** [comment]
A wild update appears!

We've switched from using a WuFoo form to using a Google Form, which is now live on the [/get-involved](http://opensourcebridge.org/get-involved/) webpage.

Other folks on the organizing team: this form and its responses exist in a "Volunteer Coordination" folder on Google Drive, which it looks like @shawnacscott, @meli-lewis, @juliepagano and some other organizer-y folks already have access to. It's unclear to me whether the heads of other committees have access to it, though, so if you don't, hit me up and I can poke around and add you.

If you want email updates when people submit responses--to scope out pre-conference assistance with stuff--you'll need to open the spreadsheet and go to `Tools > Notification rules...`. Otherwise, I can manually poke you when someone expresses interest in your committee area, I guess?

ONWARD AND UPWARD

![excited-cat](https://media.giphy.com/media/Md4xQfuJeTtx6/giphy.gif)

**Comment by kpfell** [comment]
Another wild update appears!

Not sure whether sending general volunteer requests to the main `osbridge-core` Google Group was appropriate, since people didn't really opt-in for those kinds of messages by joining, unless I'm missing something. 

Made an [`osbridge-volunteering`](https://groups.google.com/forum/#!forum/osbridge-volunteering) Google Group, in addition, where we can post pre-conference volunteer needs (stuff that isn't day-of shift work). Posts themelves should be public, but posting to the actual list requires being added to the Group.
