### ISSUE TITLE
Send volunteer recruitment email

### ISSUE THREAD

**Issue by thejensen** [osbridge/planning#402]

**Comment by ChrisFreeman** [comment]
How is this different from #372 ?

**Comment by ChrisFreeman** [comment]
Here's what I sent from volunteer@opensourcebridge.org (through gmail)

 [Logo]

The conference for open source citizens
   June 20–23, 2017 | Portland, Oregon

Thank you for your interest in volunteering at Open Source Bridge for 2017!

We need your help. OSBridge is 100% run by volunteers. 

The volunteer sign-up for 2017 is now Open!

Please visit the app at http://volunteer.opensourcebridge.org to select your shifts.

By signing up for 8 hours or more you earn a free registration to this year’s conference.

We look forward to working with you this year!

Regards, 
Chris Freeman
2017 OSBridge Volunteering

You received this email because either you had volunteered for OSBridge recently or had filled out a web form expressing your interest in volunteering.

If you no longer wish to receive email regarding volunteering at OSBridge, please reply to this email with "REMOVE" in the body or the subject.
