### ISSUE TITLE
OMG year 10

### ISSUE THREAD

**Issue by aeschright** [osbridge/planning#426]
Put all your wildest hopes and dreams right here

**Comment by elea** [comment]
Going to type in all caps not because of yelling, but because of excitement (please note that I'm purposely including ridiculous ideas):

- GOAT BOOTH / BOTTLE FEEDING
- THERAPY ALPACAS / LLAMAS / ANIMALS
- KITTEN CUDDLE CORNER
- PUPPER PETTING BREAKS
- LIVE BAND KARAOKE
- FILM SCREENINGS
- LETTERPRESSING
- GOLD FOIL
- TWO DAY CONFERENCE LENGTH MAX
- TWO TRACK MAX
- A WEBSITE THAT PROPERLY WORKS ON MOBILE

**Comment by gabelula** [comment]
. 1 day conference
. 1 day UNCONFERENCE
. Environmentally sustainable as possible across the whole event
. Secure communication between organizers and as a focus through the event
. A system that holds transparency and openness as feature of the conference.

**Comment by capnleela** [comment]
Oh, I thought this was going to be a google doc.

**Comment by reidab** [comment]
Brainstorm keynoters early, get them signed on before we start fundraising if possible.

**Comment by gabelula** [comment]
Think about what we need keynotes for.

**Comment by elea** [comment]
Ok, more serious suggestions:
- Reevaluate the format of bridge (do we want tracks? how many? what's the best number of days?)
- What is our focus in year 10 besides celebrating? Do we want a theme?
