### ISSUE TITLE
/web-badges redirection (and possibly all WP redirection) not working

### ISSUE THREAD

**Issue by reidab** [osbridge/planning#61]

**Comment by akf** [comment]
I am poking around in Wordpress (I have been reminded what my account is!) and fixed web-badges. We had a redirection for "/web-badges/" as a URL (not regexp), which was being converted to "^web-badges/$" in the .htaccess file (which the redirection tool will let you download to inspect). 

I changed it to this regexp: ^/web-badges/?$ 

But wait! /volunteer/ is working? No, we have both "/volunteer/" and "/volunteer" -- that's why it's working. 

I think, but have not verified, that something may be trimming off the / before apache gets hold of it. 

Looking for other issues in the redirection rules now.

**Comment by akf** [comment]
I've checked all the redirections except for "/^/!/?$", and fixed the few that weren't working. 

/^/!/?$ puzzles me, and I thought I was pretty good at regexes.
